import type { Metadata, Viewport } from "next";
import { Space_Grotesk, DM_Sans, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { APP_NAME } from "@/lib/branding";
import { isSiteIndexable } from "@/lib/siteFlags";

// All three faces from the design system, self-hosted via next/font: no
// third-party request, no flash of fallback type on the wordmark.
const display = Space_Grotesk({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-display",
  display: "swap",
});
const body = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-body",
  display: "swap",
});
const mono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-mono",
  display: "swap",
  // Mono dresses small badges and numbers deep in the UI, never the first
  // paint — preloading it just earned a "preloaded but not used" warning
  // on every page load.
  preload: false,
});

// generateMetadata rather than a static export for one reason: the robots
// tag follows the admin page's "visible to search engines" switch (see
// lib/siteFlags — cached, fail-closed). Everything else here is constant.
export async function generateMetadata(): Promise<Metadata> {
  const indexable = await isSiteIndexable();
  return {
    title: `${APP_NAME} — scan the whole pile, play the better deck`,
    description:
      "Scan 20+ Pokémon TCG and Magic: The Gathering cards from one photo — even mixed together — track your collection's value, and build decks with DeckAI from the cards you actually own.",
    // Until the owner flips the switch, every page says noindex — and
    // /robots.txt (app/robots.ts) reads the same flag, so the two signals
    // can never disagree.
    ...(indexable ? {} : { robots: { index: false, follow: false } }),
    // Installable: the manifest is generated by app/manifest.ts.
    manifest: "/manifest.webmanifest",
    // iOS reads none of the manifest. Its home-screen behaviour — full screen
    // with no Safari chrome, the app's own name under the icon, a dark status
    // bar over a dark header — comes from these instead.
    appleWebApp: {
      capable: true,
      title: APP_NAME,
      statusBarStyle: "black-translucent",
    },
    applicationName: APP_NAME,
    formatDetection: { telephone: false },
  };
}

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  // maximumScale: 1 was here, and it disabled pinch-zoom for everyone —
  // including on a card's artwork, which is a thing people specifically want
  // to get closer to, and including for anyone who needs to enlarge text to
  // read it at all. Locking zoom buys a marginally tidier layout at the cost
  // of the browser's most important accessibility control.
  //
  // viewportFit: "cover" lets the app paint into the notch and home-bar area
  // once it is installed; globals.css keeps content out of them with the
  // safe-area insets.
  viewportFit: "cover",
  themeColor: "#16171B",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${display.variable} ${body.variable} ${mono.variable}`}>
      {/* font-body here, not just on the marketing layout: without it the
          signed-in app fell through to the system font while the brand
          faces sat preloaded and unused. */}
      <body className="min-h-screen font-body">{children}</body>
    </html>
  );
}
