import type { Metadata, Viewport } from "next";
import { Space_Grotesk, DM_Sans, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { APP_NAME } from "@/lib/branding";

// All three faces from the design system, self-hosted via next/font: no
// third-party request, no flash of fallback type on the wordmark.
const display = Space_Grotesk({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-display",
  display: "swap",
});
const body = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-body",
  display: "swap",
});
const mono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: `${APP_NAME} — scan the whole pile, play the better deck`,
  description:
    "Scan 20+ trading cards from one photo, track your collection's value, and build decks with TrainerAI from the cards you actually own.",
  // Installable: the manifest is generated by app/manifest.ts.
  manifest: "/manifest.webmanifest",
  // iOS reads none of the manifest. Its home-screen behaviour — full screen
  // with no Safari chrome, the app's own name under the icon, a dark status
  // bar over a dark header — comes from these instead.
  appleWebApp: {
    capable: true,
    title: APP_NAME,
    statusBarStyle: "black-translucent",
  },
  applicationName: APP_NAME,
  formatDetection: { telephone: false },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  // maximumScale: 1 was here, and it disabled pinch-zoom for everyone —
  // including on a card's artwork, which is a thing people specifically want
  // to get closer to, and including for anyone who needs to enlarge text to
  // read it at all. Locking zoom buys a marginally tidier layout at the cost
  // of the browser's most important accessibility control.
  //
  // viewportFit: "cover" lets the app paint into the notch and home-bar area
  // once it is installed; globals.css keeps content out of them with the
  // safe-area insets.
  viewportFit: "cover",
  themeColor: "#16171B",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${display.variable} ${body.variable} ${mono.variable}`}>
      <body className="min-h-screen">{children}</body>
    </html>
  );
}
